MACRO(SETCPP11)
if (CMAKE_CXX_COMPILER_ID MATCHES "Intel")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
    message ("Work around for old CMAKE to work with Intel.")
elseif (CMAKE_CXX_COMPILER_ID MATCHES "nvc\\+\\+")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
    message ("Work around for old CMAKE to work with PGI.")
else ()
    set(CMAKE_CXX_STANDARD 11)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
endif()
ENDMACRO()
